export * from './Apple';
export * from './Avocado';
export * from './Banana';
export * from './Clock';
export * from './DefeatText';
export * from './Dice';
export * from './Floor';
export * from './StartText';
export * from './Wall';